export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_RECIPE = 'FETCH_RECIPE';
export const ID_TO_DISPLAY = 'ID_TO_DISPLAY';

export const PUSH_COMMENT_SUCCES = 'PUSH_COMMENT_SUCCES'
export const PUSH_COMMENT_FAILED = 'PUSH_COMMENT_FAILED'

export const PUSH_RECIPE_SUCCESS = 'PUSH_RECIPE_SUCCESS'
export const PUSH_RECIPE_FAILED = 'PUSH_RECIPE_FAILED'

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';